### ISSUE TITLE
Dependencies upgrade for mongoose-paginate

### ISSUE THREAD

**Issue by jimmysyss** [niftylettuce/eskimo#117]
I am new to eskimo, It is a great tool for my project. 

When I first start the project, the default user service http://localhost:3000/users/ is not working as expected. 

A further investigation on it reveals it is due to an upgrade of a method signature of the dependencies mongoose-paginate, the solution is changing the generated controller accordingly. 

From this line
User.paginate({}, req.query.page, req.query.limit, function(err, pageCount, users, itemCount) {

To 
User.paginate({}, {page: req.query.page, limit:req.query.limit}, function(err, users, pageCount, itemCount) {

I am looking forward to the upgrade of the eskimo generator as well. 

For details, please refer to this issue
https://github.com/edwardhotchkiss/mongoose-paginate/issues/44

**Comment by BrunoBernardino** [comment]
Hey @jimmysyss feel free to make a PR. I'll probably make one in a couple of weeks if you don't.
